### ISSUE TITLE
500 Internal Server Error on homepage

### ISSUE THREAD

**Issue by kbuffardi** [kbuffardi/CodeWitUs#61]
Upon running the container and browsing `localhost:3000` I get an Application error and the console server error reads:

```
Started GET "/" for 172.18.0.1 at 2021-12-07 22:11:42 +0000
web_1  | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  |    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1  | Processing by ApplicationController#home as HTML
web_1  |   Video Load (0.6ms)  SELECT "videos".* FROM "videos" ORDER BY RANDOM() LIMIT $1  [["LIMIT", 1]]
web_1  |   ↳ app/controllers/application_controller.rb:63:in `home'
web_1  | Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.6ms | Allocations: 2895)
web_1  | 
web_1  | 
web_1  |   
web_1  | NoMethodError (undefined method `interests' for nil:NilClass):
web_1  |   
web_1  | app/controllers/application_controller.rb:63:in `home'
```

Cannot render console is related (see #60 ) but independent of the other errors

**Comment by kbuffardi** [comment]
I believe this is primarily an issue with a (nearly) empty database and a controller that doesn't account for `nil` rows. When I run `docker-compose run web sh` and in the container run the rails console and query objects, there are no **videos**:

```shell
$ rails console
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
Running via Spring preloader in process 1515
Loading development environment (Rails 6.0.4.1)
> Interest.all
  Interest Load (0.5ms)  SELECT "interests".* FROM "interests" LIMIT $1  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Interest id: 2, interest_name: "video games\n", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 3, interest_name: "music", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 4, interest_name: "movies", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 5, interest_name: "exercise", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 6, interest_name: "books", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 7, interest_name: "outdoors", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 8, interest_name: "3D printing\n", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 9, interest_name: "photography\n", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 10, interest_name: "sports\n", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, #<Interest id: 11, interest_name: "math", created_at: "2021-12-10 00:13:21", updated_at: "2021-12-10 00:13:21", interest_count: 0>, ...]>
> Video.all()
  Video Load (2.1ms)  SELECT "videos".* FROM "videos" LIMIT $1  [["LIMIT", 11]]
=> #<ActiveRecord::Relation []>
```
So this might just need some videos seeded in the db.
